# K.NAKADA, kengo.nakada@gmail.com

# ------ Packmol ---
N_tot: 400  # セルサイズ(for packmol)
# mass_density_g_cm3: 7.35  # 質量密度
# mass_density_g_cm3: 7.3336  # 質量密度
ratios: [82, 4, 14]  # 化学量論比

# ------ RMC-DFT 基本動作設定
number_density_A3: 0.09119  # 数密度 packmol/RMC
# number_density_A3: 0.0915  # 数密度 packmol/RMC
element_info: ["Fe", "Si", "B"]  # packmol/構造変換
# element_info: "label.txt" # VASP4(Rmc.cfg) type --> VASP5 type

max_rmc_dft_loop: 10

# -------- RMC 基本動作設定
rmc_code: "RmcPot" # RMC code ClassNames
rmc_log_dir: "rmc" # log{xxx}_rmc
# rmc_log_dir: "rmc_log" # LOG 保存
#
cfg_name: "aaa" # input_file: RMC: aaa.cfg
rmc_exp_filename: "Nomag300_0305.xsq"
# OpenMP thread 数 (富岳のOMGは4つで、12コアになるので12がまぁ、良いとは思う)
rmc_omp_num_threads: 12

# RMCPOT path (パスが通ってなければフルパスで書く)
# rmc_bin: "rmcp.exe"
# rmc_bin: "/usr/local/src/RMCPOT/rmcp.exe"
# rmc_bin: "/home/u10363/rmcpot/bin/rmcp_local_fix_O2.exe"
rmc_bin: "/home/u10363/rmcpot/bin/rmcp_fugaku_fix_O2.exe"

# 入力ファイルの自動セーブ(パラメーターの変更時)
auto_write: True

# ------- DFT (VASP) 基本動作設定
dft_code: "Vasp" # VASP code ClassNames
dft_log_dir: "vasp" # log{xxx}_vasp
# dft_log_dir: "vasp_log" # LOG 保存 (for VASP)

vasp_name: "aaa" # input_file: VASP: aaa.vasp (for VASP)
# run_mode: "local"
run_mode: "mpi"
# OpenMP thread 数
dft_omp_num_threads: 1

# VASP  path
# dft_bin: "/home/hpc/vasp/bin/vasp-gamma"
# dft_bin: "/home/k/Downloads/vasp.6.4.2/bin/vasp_gam"
#dft_bin: "vasp_gam"
# dft_bin: "vasp-gamma"  # hpcs
dft_bin: "vasp_std"

# mpi: "mpirun -np {num_procs} {os.path.expanduser('/home/hpc/vasp/bin/vasp')}"
#mpi_cmd: "mpirun"
mpi_cmd: "mpiexec"

# mpi_flag
# mpi_flag: "-np"
mpi_flag: null

# MPI process 数
# num_procs: 1
num_procs: null


# -------------------------------
# default job_name
job_cmd: "qsub job_hpcs2024_node2.sh"