#!/usr/bin/env python3

from model import prepare_li3po4_recipe
from packmol import Packmol
from packmol_inp import PackmolInp


def main() -> None:
    """
    Li3PO4 の使用例。
    Li3PO4 専用処理は model.py 側で準備し、
    Packmol クラス本体は汎用のまま使う。
    """
    formula_unit_count: int = 64
    mass_density_g_cm3: float = 2.46

    packmol = Packmol(
        input_file="packmol.inp",
        output_xyz="li3po4_packmol.xyz",
        output_log="packmol.log",
        packmol_bin="packmol",
    )

    recipe = prepare_li3po4_recipe(
        formula_unit_count=formula_unit_count,
        li_xyz="Li.xyz",
        po4_xyz="PO4.xyz",
        p_o_distance=1.54,
    )

    number_density_A3: float = packmol.number_density_from_mass_density(
        symbols=recipe.symbols,
        ratios=recipe.ratios,
        mass_density_g_cm3=mass_density_g_cm3,
    )
    L: float = packmol.cell_length_from_number_density(
        N_tot=recipe.N_tot,
        number_density_A3=number_density_A3,
    )

    builder = PackmolInp(
        tolerance=1.8,
        output_xyz="li3po4_packmol.xyz",
        box_length=L,
    )
    for structure in recipe.structures:
        builder.add_structure(structure.xyz_file, structure.number)
    builder.write("packmol.inp")

    packmol.run_packmol(
        input_file="packmol.inp",
        output_log="packmol.log",
        packmol_bin="packmol",
    )

    packmol.xyz_to_poscar(
        xyz_file="li3po4_packmol.xyz",
        poscar_file="POSCAR",
        packmol_inp="packmol.inp",
        comment="Li3PO4 amorphous initial model generated by Packmol",
        elements=recipe.symbols,
    )


if __name__ == "__main__":
    main()
