#!/usr/bin/env python

from param import *
from packmol import Packmol
from packmol_inp import PackmolInp

from model import *


def prepare_Li3PO4_templates(
    formula_unit_count: int,
    li_xyz: str = "Li.xyz",
    po4_xyz: str = "PO4.xyz",
    p_o_distance: float = 1.54,
) -> Tuple[int, int, int, List[str], List[int]]:
    """
    Li3PO4 用のテンプレートと個数を準備する。
    材料依存の組み立てはクラス外の関数で扱う。
    """
    if formula_unit_count <= 0:
        raise ValueError("formula_unit_count は正の整数である必要があります。")

    write_xyz_template(
        filename=li_xyz,
        atoms=[("Li", 0.0, 0.0, 0.0)],
        comment="Li atom template",
    )
    write_po4_xyz(filename=po4_xyz, p_o_distance=p_o_distance)

    li_count: int = formula_unit_count * 3
    po4_count: int = formula_unit_count
    N_tot: int = formula_unit_count * 8
    symbols: List[str] = ["Li", "P", "O"]
    ratios: List[int] = [3, 1, 4]

    return li_count, po4_count, N_tot, symbols, ratios


def main() -> None:
    """
    Li3PO4 の使用例。
    Li3PO4 専用処理はクラス外関数で準備し、
    Packmol クラス本体は汎用のまま使う。
    """
    formula_unit_count: int = 64
    mass_density_g_cm3: float = 2.46

    packmol = Packmol(
        input_file="packmol.inp",
        output_xyz="li3po4_packmol.xyz",
        output_log="packmol.log",
        packmol_bin="packmol",
    )

    li_count, po4_count, N_tot, symbols, ratios = prepare_Li3PO4_templates(
        formula_unit_count=formula_unit_count,
        li_xyz="Li.xyz",
        po4_xyz="PO4.xyz",
        p_o_distance=1.54,
    )

    number_density_A3: float = packmol.number_density_from_mass_density(
        symbols=symbols,
        ratios=ratios,
        mass_density_g_cm3=mass_density_g_cm3,
    )
    L: float = packmol.cell_length_from_number_density(
        N_tot=N_tot,
        number_density_A3=number_density_A3,
    )

    builder = PackmolInp(
        tolerance=1.8,
        output_xyz="li3po4_packmol.xyz",
        box_length=L,
    )
    builder.add_structure("Li.xyz", li_count)
    builder.add_structure("PO4.xyz", po4_count)
    builder.write("packmol.inp")

    packmol.run_packmol(
        input_file="packmol.inp",
        output_log="packmol.log",
        packmol_bin="packmol",
    )

    packmol.xyz_to_poscar(
        xyz_file="li3po4_packmol.xyz",
        poscar_file="POSCAR",
        packmol_inp="packmol.inp",
        comment="Li3PO4 amorphous initial model generated by Packmol",
        elements=["Li", "P", "O"],
    )


if __name__ == "__main__":
    main()
