#!/usr/bin/env python

from param import *
from packmol import Packmol
from packmol_inp import PackmolInp

from model import *


def prepare_FeSiB_templates(
    total_atom_count: int,
    fe_xyz: str = "Fe.xyz",
    si_xyz: str = "Si.xyz",
    b_xyz: str = "B.xyz",
) -> Tuple[int, int, int, List[str], List[int]]:
    """
    FeSiB 用の単原子テンプレートと個数を準備する。
    """
    if total_atom_count <= 0:
        raise ValueError("total_atom_count は正の整数である必要があります。")

    symbols: List[str] = ["Fe", "Si", "B"]
    ratios: List[int] = [80, 9, 11]

    ratio_sum: int = sum(ratios)
    if total_atom_count % ratio_sum != 0:
        raise ValueError(
            "total_atom_count は Fe80Si9B11 の比率合計 100 の整数倍である必要があります。"
        )

    multiplier: int = total_atom_count // ratio_sum

    fe_count: int = ratios[0] * multiplier
    si_count: int = ratios[1] * multiplier
    b_count: int = ratios[2] * multiplier

    write_xyz_template(
        filename=fe_xyz,
        atoms=[("Fe", 0.0, 0.0, 0.0)],
        comment="Fe atom template",
    )
    write_xyz_template(
        filename=si_xyz,
        atoms=[("Si", 0.0, 0.0, 0.0)],
        comment="Si atom template",
    )
    write_xyz_template(
        filename=b_xyz,
        atoms=[("B", 0.0, 0.0, 0.0)],
        comment="B atom template",
    )

    return fe_count, si_count, b_count, symbols, ratios


def main() -> None:
    """
    FeSiB の使用例。
    FeSiB 専用処理は model.py 側で準備し、
    Packmol クラス本体は汎用のまま使う。
    """
    total_atom_count: int = 100
    mass_density_g_cm3: float = 7.0

    packmol = Packmol(
        input_file="packmol.inp",
        output_xyz="fesib_packmol.xyz",
        output_log="packmol.log",
        packmol_bin="packmol",
    )

    fe_count, si_count, b_count, symbols, ratios = prepare_FeSiB_templates(
        total_atom_count=total_atom_count,
        fe_xyz="Fe.xyz",
        si_xyz="Si.xyz",
        b_xyz="B.xyz",
    )

    number_density_A3: float = packmol.number_density_from_mass_density(
        symbols=symbols,
        ratios=ratios,
        mass_density_g_cm3=mass_density_g_cm3,
    )
    L: float = packmol.cell_length_from_number_density(
        N_tot=total_atom_count,
        number_density_A3=number_density_A3,
    )

    builder = PackmolInp(
        tolerance=2.3,
        output_xyz="fesib_packmol.xyz",
        box_length=L,
    )
    builder.add_structure("Fe.xyz", fe_count)
    builder.add_structure("Si.xyz", si_count)
    builder.add_structure("B.xyz", b_count)
    builder.write("packmol.inp")

    packmol.run_packmol(
        input_file="packmol.inp",
        output_log="packmol.log",
        packmol_bin="packmol",
    )

    packmol.xyz_to_poscar(
        xyz_file="fesib_packmol.xyz",
        poscar_file="POSCAR",
        packmol_inp="packmol.inp",
        comment="FeSiB amorphous initial model generated by Packmol",
        elements=["Fe", "Si", "B"],
    )


if __name__ == "__main__":
    main()
