#!/usr/bin/env python3

from model import prepare_fesib_recipe
from packmol import Packmol
from packmol_inp import PackmolInp


def main() -> None:
    """
    FeSiB の使用例。
    FeSiB 専用処理は model.py 側で準備し、
    Packmol クラス本体は汎用のまま使う。
    """
    N_tot: int = 100
    mass_density_g_cm3: float = 7.0

    packmol = Packmol(
        input_file="packmol.inp",
        output_xyz="fesib_packmol.xyz",
        output_log="packmol.log",
        packmol_bin="packmol",
    )

    recipe = prepare_fesib_recipe(
        N_tot=N_tot,
        fe_xyz="Fe.xyz",
        si_xyz="Si.xyz",
        b_xyz="B.xyz",
    )

    number_density_A3: float = packmol.number_density_from_mass_density(
        symbols=recipe.symbols,
        ratios=recipe.ratios,
        mass_density_g_cm3=mass_density_g_cm3,
    )
    L: float = packmol.cell_length_from_number_density(
        N_tot=recipe.N_tot,
        number_density_A3=number_density_A3,
    )

    builder = PackmolInp(
        tolerance=2.3,
        output_xyz="fesib_packmol.xyz",
        box_length=L,
    )
    for structure in recipe.structures:
        builder.add_structure(structure.xyz_file, structure.number)
    builder.write("packmol.inp")

    packmol.run_packmol(
        input_file="packmol.inp",
        output_log="packmol.log",
        packmol_bin="packmol",
    )

    packmol.xyz_to_poscar(
        xyz_file="fesib_packmol.xyz",
        poscar_file="POSCAR",
        packmol_inp="packmol.inp",
        comment="FeSiB amorphous initial model generated by Packmol",
        elements=recipe.symbols,
    )


if __name__ == "__main__":
    main()
