#!/usr/bin/env python3

from model import StructureSpec
from model import make_material_recipe
from model import write_single_atom_xyz
from model import write_tetrahedral_unit_xyz
from packmol import Packmol
from packmol_inp import PackmolInp


def main() -> None:
    """
    Li3PO4 の使用例。
    物質固有パラメーターはこのスクリプト内で与える。
    """
    formula_unit_count: int = 64
    number_density_A3: float = 0.0772877
    p_o_distance: float = 1.54

    li_xyz: str = "Li.xyz"
    po4_xyz: str = "PO4.xyz"
    output_xyz: str = "li3po4_packmol.xyz"
    input_file: str = "packmol.inp"
    output_log: str = "packmol.log"
    poscar_file: str = "POSCAR"
    packmol_bin: str = "packmol"

    symbols = ["Li", "P", "O"]
    ratios = [3, 1, 4]

    li_count: int = formula_unit_count * 3
    po4_count: int = formula_unit_count

    po4_atom_radii = {
        1: 0.25,
        2: 1.05,
        3: 1.05,
        4: 1.05,
        5: 1.05,
    }

    packmol = Packmol(
        input_file=input_file,
        output_xyz=output_xyz,
        output_log=output_log,
        packmol_bin=packmol_bin,
    )

    write_single_atom_xyz(filename=li_xyz, element="Li")
    write_tetrahedral_unit_xyz(
        filename=po4_xyz,
        center_element="P",
        vertex_element="O",
        center_vertex_distance=p_o_distance,
    )

    recipe = make_material_recipe(
        symbols=symbols,
        ratios=ratios,
        structures=[
            StructureSpec(xyz_file=li_xyz, number=li_count),
            StructureSpec(
                xyz_file=po4_xyz,
                number=po4_count,
                atom_radii=po4_atom_radii,
            ),
        ],
    )

    L: float = packmol.cell_length_from_number_density(
        N_tot=recipe.N_tot,
        number_density_A3=number_density_A3,
    )

    builder = PackmolInp(
        tolerance=1.8,
        output_xyz=output_xyz,
        box_length=L,
        use_pbc=True,
    )
    for structure in recipe.structures:
        builder.add_structure(
            xyz_file=structure.xyz_file,
            number=structure.number,
            atom_radii=structure.atom_radii,
        )
    builder.write(input_file)

    packmol.run_packmol(
        input_file=input_file,
        output_log=output_log,
        packmol_bin=packmol_bin,
    )

    packmol.xyz_to_poscar(
        xyz_file=output_xyz,
        poscar_file=poscar_file,
        packmol_inp=input_file,
        comment="Li3PO4 amorphous initial model generated by Packmol",
        elements=recipe.symbols,
    )


if __name__ == "__main__":
    main()
