#!/usr/bin/env python3

from model import make_atomic_mixture_recipe
from packmol import Packmol
from packmol_inp import PackmolInp


def main() -> None:
    """
    FeSiB の使用例。
    物質固有パラメーターはこのスクリプト内で与える。
    """
    N_tot: int = 100
    mass_density_g_cm3: float = 7.0

    symbols = ["Fe", "Si", "B"]
    ratios = [80, 9, 11]
    xyz_files = ["Fe.xyz", "Si.xyz", "B.xyz"]

    input_file: str = "packmol.inp"
    output_xyz: str = "fesib_packmol.xyz"
    output_log: str = "packmol.log"
    poscar_file: str = "POSCAR"
    packmol_bin: str = "packmol"

    packmol = Packmol(
        input_file=input_file,
        output_xyz=output_xyz,
        output_log=output_log,
        packmol_bin=packmol_bin,
    )

    recipe = make_atomic_mixture_recipe(
        symbols=symbols,
        ratios=ratios,
        N_tot=N_tot,
        xyz_files=xyz_files,
    )

    number_density_A3: float = packmol.number_density_from_mass_density(
        symbols=recipe.symbols,
        ratios=recipe.ratios,
        mass_density_g_cm3=mass_density_g_cm3,
    )
    L: float = packmol.cell_length_from_number_density(
        N_tot=recipe.N_tot,
        number_density_A3=number_density_A3,
    )

    builder = PackmolInp(
        tolerance=2.3,
        output_xyz=output_xyz,
        box_length=L,
    )
    for structure in recipe.structures:
        builder.add_structure(
            xyz_file=structure.xyz_file,
            number=structure.number,
            atom_radii=structure.atom_radii,
        )
    builder.write(input_file)

    packmol.run_packmol(
        input_file=input_file,
        output_log=output_log,
        packmol_bin=packmol_bin,
    )

    packmol.xyz_to_poscar(
        xyz_file=output_xyz,
        poscar_file=poscar_file,
        packmol_inp=input_file,
        comment="FeSiB amorphous initial model generated by Packmol",
        elements=recipe.symbols,
    )


if __name__ == "__main__":
    main()
