name: Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install sphinx myst-parser sphinx-rtd-theme linkify-it-py

      - name: Build Sphinx
        working-directory: docs
        run: |
          export LANG=C.UTF-8
          export LC_ALL=C.UTF-8
          bash build.sh

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
